---
- hosts: all
  
  tasks:
  - name: Download asset
    local_action: 
      module: get_url
      #url: http://speedtest-ny.turnkeyinternet.net/1000mb.bin
      url: http://speedtest-ny.turnkeyinternet.net/100mb.bin
      dest: "{{ playbook_dir }}/100mb.zip"
  
  - name: What is in the playbook_dir?
    local_action:
      module: command ls {{ playbook_dir }}
    register: playbookdircontents
    
  - debug:
      var: "{{ item }}"
    with_items: playbookdircontents.stdout_lines
  
  - name: set_fact for winrm to 5985
    set_fact:
      ansible_port: 5985
  
  - name: win_copy to windows host
    win_copy:
      src: "{{ playbook_dir }}/100mb.zip"
      dest: C:\webapps\

  - name: set_fact for winrm to 5986
    set_fact:
      ansible_port: 5986
